import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./_context/cart";
import AuthProvider from "./_providers/auth";
import { Toaster } from "./_components/ui/sonner";
import Footer from "./_components/footer";

export const metadata: Metadata = {
  title: "DEV Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>

        <Toaster />
      </body>
    </html>
  );
}
