import type { Metadata } from "next";
import { Toaster } from "sonner";
import "../globals.css";
import AuthProvider from "@/app/_providers/auth";

export const metadata: Metadata = {
  title: "DEV Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col bg-gray-100">
        <AuthProvider>
          <div className="flex flex-1">
            <div className="flex-1 p-4">{children}</div>
          </div>
        </AuthProvider>

        <Toaster />
      </body>
    </html>
  );
}
