import type { Metadata } from "next";
import { Toaster } from "sonner";
import "../globals.css";
import AuthProvider from "@/app/_providers/auth";
import { getServerSession } from "next-auth";
import { authOptions } from "../_lib/auth";
import { redirect } from "next/navigation";
import AdminSidebar from "./_components/admin-sidebar";

export const metadata: Metadata = {
  title: "DEV Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session || session.user.isAdmin === false) return redirect("/");

  return (
    <html lang="en">
      <body className="flex h-screen flex-col bg-gray-100 lg:flex-row">
        <AuthProvider>
          <AdminSidebar />
          <div className="flex-1">{children}</div>
        </AuthProvider>

        <Toaster />
      </body>
    </html>
  );
}
